"""
Legal Notice PDF Generator using ReportLab.
Generates a formal Hinglish/English notice addressed to the District Labour Officer.
"""
from io import BytesIO
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
import logging

logger = logging.getLogger(__name__)

def generate_legal_notice_pdf(report, worker_phone_hash: str) -> BytesIO:
    """
    Generate a formal legal notice PDF for wage theft in memory.
    Using Hinglish to avoid Devanagari font rendering issues in ReportLab defaults.
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    
    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 750, "LEGAL NOTICE - WAGE THEFT (BOCW ACT 1996)")
    
    c.setFont("Helvetica", 12)
    c.drawString(100, 720, f"Date: {datetime.utcnow().strftime('%Y-%m-%d')}")
    c.drawString(100, 700, "To,")
    c.drawString(100, 680, "The District Labour Officer")
    c.drawString(100, 660, f"District: {report.district}, {report.state}")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 620, "Subject: Formal Complaint Regarding Underpayment of Minimum Wages")
    
    c.setFont("Helvetica", 12)
    c.drawString(100, 580, "Respected Sir/Madam,")
    c.drawString(100, 550, "Yeh ek formal notice hai regarding Minimum Wages Act 1948")
    c.drawString(100, 530, "aur BOCW Act 1996 ke violations ke baare mein.")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 490, "Worker Details:")
    c.setFont("Helvetica", 12)
    c.drawString(120, 470, f"- Worker ID (Hash): {worker_phone_hash}")
    c.drawString(120, 450, f"- Occupation: {report.occupation}")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 410, "Contractor / Employer Details:")
    c.setFont("Helvetica", 12)
    c.drawString(120, 390, f"- Contractor ID: {report.contractor_id or 'Unknown'}")
    c.drawString(120, 370, f"- Location: {report.district}, {report.state}")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 330, "Wage Discrepancy (Per Day):")
    c.setFont("Helvetica", 12)
    c.drawString(120, 310, f"- Government Mandated Fair Wage: Rs. {report.fair_wage}")
    c.drawString(120, 290, f"- Actual Paid Wage: Rs. {report.reported_wage}")
    c.drawString(120, 270, f"- Wage Gap (Theft): Rs. {report.wage_gap}")
    
    c.drawString(100, 230, "Kripya is maamle ki jaanch karein aur bakaaya mazdoori")
    c.drawString(100, 210, "dilwaane mein sahayata karein.")
    
    c.drawString(100, 150, "Generated by:")
    c.drawString(100, 130, "Suraksha Chakra AI Legal Cell")
    
    # Signature line
    c.line(100, 100, 250, 100)
    c.drawString(100, 85, "Authorized Signature (Placeholder)")
    
    c.save()
    buffer.seek(0)
    return buffer
